### ISSUE TITLE
Please make releases 

### ISSUE THREAD

**Issue by baldurmen** [dmcanally/denver-netdata#12]
Hi,

Thanks for this module! It it really helpful.

Would it be possible to make releases instead of just pushing to the master branch? It would certainly help me keep track of changes made to this module :)

**Comment by dmcanally** [comment]
I'm happy to add tags to the branches to specify releases. I had simply been relying on forge to store versions. I'll start with my next build with all the changes you made.

**Comment by dmcanally** [comment]
I created the release for 0.2.1. I'll be sure to do so for future releases.

Thanks,
Denver

**Comment by baldurmen** [comment]
Thanks!
